apiVersion: nats-operator.io/v1beta1
kind: NatsAccountTrust
metadata:
  name: orders
  namespace: nats-system
spec:
  publicKey: AORDERS...
  jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ...
---
apiVersion: nats-operator.io/v1beta1
kind: NatsAccountTrust
metadata:
  name: payments
  namespace: nats-system
spec:
  publicKey: APAYMENTS...
  jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ...
