apiVersion: cluster.nats-operator.io/v1beta1
kind: NatsCluster
metadata:
  name: west
  namespace: nats-system
spec:
  version: 2.15.0
  replicas: 3
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      memory: 4Gi
  jetstream:
    volumeClaimTemplate:
      spec:
        storageClassName: gp3
        resources:
          requests:
            storage: 100Gi
  auth:
    trustRef:
      name: central
    systemCredentials:
      secretKeyRef:
        name: west-cluster-controller-creds
    accountTrustRefs:
      - name: orders
      - name: payments
  gateway:
    discovery: Explicit
    remotes:
      - name: central
        url: nats://nats-central.example.net:7222
      - name: west
        url: nats://nats-west.example.net:7222
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: nats-west.example.net
    advertise: nats-west.example.net:7222
