apiVersion: nats.mikluko.io/v1beta1
kind: NatsConnection
metadata:
  name: west
  namespace: orders
spec:
  servers: ["nats://west.nats-system.svc:4222"]
  credentials:
    secretKeyRef:
      name: orders-creds
