// Package fixtures generates the files of a story's e2e/ directory that hold
// keys, each generated afresh and guarding nothing but the run. nsc cannot
// stand in: it writes keys and JWTs to its own store, not Secret manifests,
// and does not expand jwtplane's presets.
package fixtures

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/nats-io/jwt/v2"
	"github.com/nats-io/nkeys"

	"github.com/mikluko/nats-operator/internal/jwtplane"
)

// generators write a story's fixtures into dir, with the patch files of the
// substitutions that take generated values, keyed by the story's directory.
var generators = map[string]func(dir string) error{
	"03-unmanaged":         unmanaged,
	"06-supercluster":      supercluster,
	"09-acceptance":        acceptance,
	"10-leafnodes":         leafnodes,
	"11-evacuation":        evacuation,
	"13-join-supercluster": joinSupercluster,
	"14-nsc-adoption":      adoption,
}

// Generate writes every story's fixtures into root/<story>/e2e, root laid
// out as the stories directory is.
func Generate(root string) error {
	for story, gen := range generators {
		dir := filepath.Join(root, story, "e2e")
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return err
		}
		if err := gen(dir); err != nil {
			return fmt.Errorf("%s: %w", story, err)
		}
	}
	return nil
}

// funcs are the template functions every template here may call.
var funcs = template.FuncMap{
	"dict": func(kv ...string) map[string]string {
		m := map[string]string{}
		for i := 0; i+1 < len(kv); i += 2 {
			m[kv[i]] = kv[i+1]
		}
		return m
	},
	"secret": func(name, namespace string, lines []string) secret {
		return secret{Name: name, Namespace: namespace, Lines: lines}
	},
}

// writeTemplate writes t executed on data to dir/name, readable by its owner
// alone.
func writeTemplate(dir, name string, t *template.Template, data any) error {
	f, err := os.OpenFile(filepath.Join(dir, name), os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return err
	}
	if err := t.Execute(f, data); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// writePatch writes spec as the JSON merge patch {"spec": spec} to dir/name.
func writePatch(dir, name string, spec map[string]string) error {
	raw, err := json.Marshal(map[string]any{"spec": spec})
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, name), append(raw, '\n'), 0o600)
}

// keys generates an identity and one signing key, signing-1, of kind, and
// returns them with their seeds in that order.
func keys(kind nkeys.PrefixByte) (jwtplane.Keys, [2]string, error) {
	var seeds [2]string
	var pairs [2]nkeys.KeyPair
	for i := range pairs {
		seed, err := jwtplane.GenerateSeed(kind)
		if err != nil {
			return jwtplane.Keys{}, seeds, err
		}
		if pairs[i], err = jwtplane.ParseSeed(seed, kind); err != nil {
			return jwtplane.Keys{}, seeds, err
		}
		seeds[i] = string(seed)
	}
	return jwtplane.Keys{Identity: pairs[0], Signing: []jwtplane.SigningKey{{Name: "signing-1", Pair: pairs[1]}}}, seeds, nil
}

// userCreds signs u, a new user of account, and returns its creds file
// line by line.
func userCreds(u jwtplane.User, account jwtplane.Keys) ([]string, error) {
	kp, err := nkeys.CreateUser()
	if err != nil {
		return nil, err
	}
	if u.PublicKey, err = kp.PublicKey(); err != nil {
		return nil, err
	}
	token, err := jwtplane.SignUser(u, account)
	if err != nil {
		return nil, err
	}
	seed, err := kp.Seed()
	if err != nil {
		return nil, err
	}
	creds, err := jwt.FormatUserConfig(token, seed)
	if err != nil {
		return nil, err
	}
	return strings.Split(strings.TrimRight(string(creds), "\n"), "\n"), nil
}

// generated heads every YAML fixture this package writes.
const generated = "# Generated by internal/e2e/fixtures; the keys guard only this fixture.\n"

// secret is what credsSecret renders.
type secret struct {
	Name, Namespace string
	Lines           []string
}

// credsSecret renders a Secret holding creds lines under user.creds.
const credsSecret = `apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
stringData:
  user.creds: |
{{range $line := .Lines}}{{if $line}}    {{$line}}{{end}}
{{end}}`

// partials are the templates every fixture may call.
const partials = `{{define "keys"}}apiVersion: v1
kind: Secret
metadata:
  name: {{.name}}-keys
  namespace: nats-system
stringData:
  identity: {{.identity}}
  signing-1: {{.signing}}
{{end}}{{define "adopt"}}  keys:
    identity:
      secretKeyRef: {name: {{.}}-keys, key: identity}
    signing:
      - name: signing-1
        secretKeyRef: {name: {{.}}-keys, key: signing-1}
{{end}}{{define "systemAccount"}}apiVersion: auth.nats-operator.io/v1beta1
kind: NatsSystemAccount
metadata:
  name: sys
  namespace: nats-system
spec:
  operatorRef:
    name: acme
{{template "adopt" "sys"}}{{end}}{{define "sysuser"}}apiVersion: auth.nats-operator.io/v1beta1
kind: NatsUser
metadata:
  name: {{.}}
  namespace: nats-system
spec:
  accountRef:
    kind: NatsSystemAccount
    name: sys
  preset: {{.}}
  credentials:
    secretKeyRef:
      name: {{.}}-creds
{{end}}{{define "secret"}}` + credsSecret + `{{end}}`

// parseFixture parses body, headed by generated, as the template name with
// funcs and partials.
func parseFixture(name, body string) *template.Template {
	return template.Must(template.Must(template.New(name).Funcs(funcs).Parse(generated + body)).Parse(partials))
}
