{{- if .Values.auth.enabled }}
{{- $args := list }}
{{- with .Values.auth.systemConnection }}
{{- $args = append $args (printf "--system-connection=%s" .) }}
{{- end }}
{{- include "nats-operator.controller" (dict "root" . "name" "auth-controller" "group" "auth.nats.mikluko.io" "values" .Values.auth "args" $args) }}
{{- end }}
