apiVersion: auth.nats-operator.io/v1beta1
kind: NatsAccount
metadata:
  name: monitoring
  namespace: nats-system
spec:
  operatorRef:
    name: demo
  exports:
    - name: check-results
      type: Stream
      subject: "monitoring.results.>"
    - name: execute
      type: Service
      subject: "monitoring.execute"
      responseType: Singleton
      access: Private
      importers:
        - kind: NatsAccount
          name: core
