apiVersion: auth.nats-operator.io/v1beta1
kind: NatsAccount
metadata:
  name: core
  namespace: nats-system
spec:
  operatorRef:
    name: demo
  imports:
    - accountRef:
        kind: NatsAccount
        name: monitoring
      export: check-results
      localSubject: "upstream.results.>"
    - accountRef:
        kind: NatsAccount
        name: monitoring
      export: execute
