{{- define "packages" -}}
---
title: API reference
description: Every kind, field and value of the four API groups at v1beta1.
weight: 1
---
Generated by `just api-docs` from the Go types under `api/`.
{{ range .packages }}
## {{ packageDisplayName . | safe }}
{{ with (index .GoPackages 0) }}{{ template "doc" .DocComments }}{{ end }}
| Kind | Description |
| :--- | :---------- |
{{- range (visibleTypes (sortedTypes .Types)) }}
{{- $kind := false }}
{{- range .SecondClosestCommentLines }}{{ if eq . "+kubebuilder:object:root=true" }}{{ $kind = true }}{{ end }}{{ end }}
{{- range .CommentLines }}{{ if eq . "+kubebuilder:object:root=true" }}{{ $kind = true }}{{ end }}{{ end }}
{{- if $kind }}
| [{{ .Name.Name | safe }}](#{{ .Name.Name | safe }}) | {{ template "doc" .CommentLines }} |
{{- end }}
{{- end }}
{{ range (visibleTypes (sortedTypes .Types)) }}
{{- template "type" . }}
{{- end }}
{{- end }}
{{- end }}

{{- /* doc renders comment lines as one line of prose, markers left out. */ -}}
{{- define "doc" -}}
{{- $first := true -}}
{{- range . -}}
{{- if and (gt (len .) 0) (ne (slice . 0 1) "+") -}}
{{- if not $first }} {{ end -}}
{{- $first = false -}}
{{- safe . -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- /* badge renders a type name with the Hudocs type shortcode. */ -}}
{{- define "badge" -}}
{{- safe "{{< type \"" }}{{ safe . }}{{ safe "\" >}}" -}}
{{- end -}}

{{- /* typelink renders a type's badge, linked to its section or its Go documentation. */ -}}
{{- define "typelink" -}}
{{- $link := linkForType . -}}
{{- if not $link -}}
{{ template "badge" (typeDisplayName .) }}
{{- else if eq (slice $link 0 1) "#" -}}
[{{ template "badge" (typeDisplayName .) }}](#{{ if .Elem }}{{ .Elem.Name.Name | safe }}{{ else }}{{ .Name.Name | safe }}{{ end }})
{{- else -}}
[{{ template "badge" (typeDisplayName .) }}]({{ safe $link }})
{{- end -}}
{{- end -}}
