{{- define "gvList" -}}
---
title: API reference
description: Every kind, field and value of the four API groups at v1beta1.
weight: 1
---

<!-- Generated by `just api-docs` from the Go types under `api/`. -->
{{ range . }}
## {{ .GroupVersionString }}
{{ template "doc" .Doc }}
| Kind | Description |
| :--- | :---------- |
{{- $gv := . }}
{{- range .SortedKinds }}
| [{{ . }}](#{{ . }}) | {{ template "doc" ($gv.TypeForKind .).Doc }} |
{{- end }}
{{ range .SortedTypes }}
{{- template "type" . }}
{{- end }}
{{- end }}
{{- end }}

{{- /* doc renders a doc comment as one line of prose. */ -}}
{{- define "doc" -}}
{{- . | trim | replace "\n" " " -}}
{{- end -}}

{{- /* badge renders a type name with the Hudocs type shortcode. */ -}}
{{- define "badge" -}}
{{ "{{< type \"" }}{{ . }}{{ "\" >}}" }}
{{- end -}}

{{- /* typename renders a type as Go spells it, pointers dereferenced and
       packages left out. Kind values are crd-ref-docs' types.Kind:
       0 alias, 3 map, 4 pointer, 5 slice. */ -}}
{{- define "typename" -}}
{{- if eq .Kind 5 }}[]{{ template "typename" .UnderlyingType }}
{{- else if eq .Kind 4 }}{{ template "typename" .UnderlyingType }}
{{- else if eq .Kind 3 }}map[{{ template "typename" .KeyType }}]{{ template "typename" .ValueType }}
{{- else }}{{ .Name }}
{{- end -}}
{{- end -}}

{{- /* typebadge renders a type's name with the Hudocs type shortcode. */ -}}
{{- define "typebadge" -}}
{{ "{{< type \"" }}{{ template "typename" . }}{{ "\" >}}" }}
{{- end -}}

{{- /* typelink renders a type's badge, linked to the section or the Go
       documentation of its element type. */ -}}
{{- define "typelink" -}}
{{- $e := . -}}
{{- range until 3 -}}
{{- if or (eq $e.Kind 4) (eq $e.Kind 5) }}{{ $e = $e.UnderlyingType }}{{ else if eq $e.Kind 3 }}{{ $e = $e.ValueType }}{{ end -}}
{{- end -}}
{{- $link := "" -}}
{{- if hasPrefix "github.com/mikluko/nats-operator/api/" $e.Package }}{{ $link = print "#" $e.Name }}
{{- else if hasPrefix "k8s.io/" $e.Package }}{{ $link = print "https://pkg.go.dev/" $e.Package "#" $e.Name }}
{{- end -}}
{{- if $link }}[{{ template "typebadge" . }}]({{ $link }}){{ else }}{{ template "typebadge" . }}{{ end -}}
{{- end -}}
