// Command e2e-fixtures writes into a story's e2e/ directory the fixture
// files its e2e run stands on, every key generated afresh and guarding
// nothing but the run:
//
//	go run ./hack/e2e-fixtures <story number> docs/content/docs/stories/<story>/e2e
//
// Where the story's substitutions take generated values, it prints them as
// a substitution's patch. nsc cannot stand in: it writes keys and JWTs to its
// own store, not the Secret manifests a story applies.
package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/nats-io/jwt/v2"
	"github.com/nats-io/nkeys"

	"github.com/mikluko/nats-operator/internal/jwtplane"
)

// generators write a story's fixtures into dir and the substitutions they
// take to out, keyed by story number.
var generators = map[string]func(dir string, out io.Writer) error{
	"3":  unmanaged,
	"6":  supercluster,
	"9":  acceptance,
	"10": leafnodes,
	"11": evacuation,
}

// funcs are the template functions every template here may call: dict
// builds a map from key, value pairs, and secret a credsSecret's data.
var funcs = template.FuncMap{
	"dict": func(kv ...string) map[string]string {
		m := map[string]string{}
		for i := 0; i+1 < len(kv); i += 2 {
			m[kv[i]] = kv[i+1]
		}
		return m
	},
	"secret": func(name, namespace string, lines []string) secret {
		return secret{Name: name, Namespace: namespace, Lines: lines}
	},
}

func main() {
	if len(os.Args) != 3 {
		_, _ = fmt.Fprintln(os.Stderr, "usage: e2e-fixtures <story number> <story e2e directory>")
		os.Exit(2)
	}
	gen, ok := generators[os.Args[1]]
	if !ok {
		_, _ = fmt.Fprintf(os.Stderr, "e2e-fixtures: story %s has no fixtures\n", os.Args[1])
		os.Exit(2)
	}
	if err := gen(os.Args[2], os.Stdout); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, "e2e-fixtures:", err)
		os.Exit(1)
	}
}

// writeTemplate writes t executed on data to dir/name.
func writeTemplate(dir, name string, t *template.Template, data any) error {
	f, err := os.Create(filepath.Join(dir, name))
	if err != nil {
		return err
	}
	if err := t.Execute(f, data); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// keys generates an identity and one signing key, signing-1, of kind, and
// returns them with their seeds in that order.
func keys(kind nkeys.PrefixByte) (jwtplane.Keys, [2]string, error) {
	var seeds [2]string
	var pairs [2]nkeys.KeyPair
	for i := range pairs {
		seed, err := jwtplane.GenerateSeed(kind)
		if err != nil {
			return jwtplane.Keys{}, seeds, err
		}
		if pairs[i], err = jwtplane.ParseSeed(seed, kind); err != nil {
			return jwtplane.Keys{}, seeds, err
		}
		seeds[i] = string(seed)
	}
	return jwtplane.Keys{Identity: pairs[0], Signing: []jwtplane.SigningKey{{Name: "signing-1", Pair: pairs[1]}}}, seeds, nil
}

// userCreds signs u, a new user of account, and returns its creds file
// line by line.
func userCreds(u jwtplane.User, account jwtplane.Keys) ([]string, error) {
	kp, err := nkeys.CreateUser()
	if err != nil {
		return nil, err
	}
	if u.PublicKey, err = kp.PublicKey(); err != nil {
		return nil, err
	}
	token, err := jwtplane.SignUser(u, account)
	if err != nil {
		return nil, err
	}
	seed, err := kp.Seed()
	if err != nil {
		return nil, err
	}
	creds, err := jwt.FormatUserConfig(token, seed)
	if err != nil {
		return nil, err
	}
	return strings.Split(strings.TrimRight(string(creds), "\n"), "\n"), nil
}

// generated heads every file this command writes.
const generated = "# Generated by hack/e2e-fixtures; the keys guard only this fixture.\n"

// secret is what credsSecret renders.
type secret struct {
	Name, Namespace string
	Lines           []string
}

// credsSecret renders a Secret holding creds lines under user.creds.
const credsSecret = `apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
stringData:
  user.creds: |
{{range $line := .Lines}}{{if $line}}    {{$line}}{{end}}
{{end}}`
