apiVersion: jetstream.nats-operator.io/v1beta1
kind: NatsStream
metadata:
  name: payments
  namespace: payments
spec:
  connectionRef:
    name: shared-payments
  adoptionPolicy: Adopt
  name: PAYMENTS
---
apiVersion: jetstream.nats-operator.io/v1beta1
kind: NatsStream
metadata:
  name: refunds
  namespace: payments
spec:
  connectionRef:
    name: shared-payments
  adoptionPolicy: AdoptOrCreate
  name: REFUNDS
  subjects: ["refunds.>"]
  storage: File
  replicas: 3
  maxAge: 2160h
---
apiVersion: jetstream.nats-operator.io/v1beta1
kind: NatsStream
metadata:
  name: ledger
  namespace: payments
spec:
  connectionRef:
    name: shared-payments
  terminalPolicy: Retry
  name: LEDGER
  subjects: ["ledger.>"]
  replicas: 3
