apiVersion: nats-operator.io/v1beta1
kind: NatsConnection
metadata:
  name: shared-payments
  namespace: payments
spec:
  servers: ["tls://nats.messaging.svc:4222"]
  tls:
    ca:
      secretKeyRef:
        name: messaging-nats-ca
  credentials:
    secretKeyRef:
      name: payments-secrets
      key: nats.creds
