apiVersion: jetstream.nats.mikluko.io/v1beta1
kind: NatsBalancer
metadata:
  name: payments
  namespace: payments
spec:
  connectionRef:
    name: demo
  pools:
    - name: requests
      selector:
        matchLabels:
          traffic: requests
    - name: responses
      selector:
        matchLabels:
          traffic: responses
  moves:
    leader: true
    placement: false
---
apiVersion: jetstream.nats.mikluko.io/v1beta1
kind: NatsStream
metadata:
  name: req-07
  namespace: payments
  labels:
    traffic: requests
spec:
  connectionRef:
    name: demo
  name: REQ_07
  subjects: ["req.07.>"]
  replicas: 3
