apiVersion: nats.mikluko.io/v1beta1
kind: NatsConnection
metadata:
  name: demo-sys
  namespace: nats-system
spec:
  servers: ["nats://demo.nats-system.svc:4222"]
  credentials:
    secretKeyRef:
      name: jetstream-controller-creds
---
apiVersion: jetstream.nats.mikluko.io/v1beta1
kind: NatsSystemBalancer
metadata:
  name: demo
  namespace: nats-system
spec:
  connectionRef:
    name: demo-sys
  moves:
    placement: true
    leader: true
  interval: 1m
