//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	natsv1beta1 "github.com/mikluko/nats-operator/api/nats/v1beta1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Capabilities) DeepCopyInto(out *Capabilities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Capabilities.
func (in *Capabilities) DeepCopy() *Capabilities {
	if in == nil {
		return nil
	}
	out := new(Capabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerConfig) DeepCopyInto(out *ConsumerConfig) {
	*out = *in
	if in.DeliverPolicy != nil {
		in, out := &in.DeliverPolicy, &out.DeliverPolicy
		*out = new(DeliverPolicy)
		**out = **in
	}
	if in.OptStartSeq != nil {
		in, out := &in.OptStartSeq, &out.OptStartSeq
		*out = new(int64)
		**out = **in
	}
	if in.OptStartTime != nil {
		in, out := &in.OptStartTime, &out.OptStartTime
		*out = (*in).DeepCopy()
	}
	if in.AckPolicy != nil {
		in, out := &in.AckPolicy, &out.AckPolicy
		*out = new(AckPolicy)
		**out = **in
	}
	if in.AckWait != nil {
		in, out := &in.AckWait, &out.AckWait
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxDeliver != nil {
		in, out := &in.MaxDeliver, &out.MaxDeliver
		*out = new(int64)
		**out = **in
	}
	if in.BackOff != nil {
		in, out := &in.BackOff, &out.BackOff
		*out = make([]v1.Duration, len(*in))
		copy(*out, *in)
	}
	if in.FilterSubjects != nil {
		in, out := &in.FilterSubjects, &out.FilterSubjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReplayPolicy != nil {
		in, out := &in.ReplayPolicy, &out.ReplayPolicy
		*out = new(ReplayPolicy)
		**out = **in
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(int64)
		**out = **in
	}
	if in.MaxWaiting != nil {
		in, out := &in.MaxWaiting, &out.MaxWaiting
		*out = new(int64)
		**out = **in
	}
	if in.MaxAckPending != nil {
		in, out := &in.MaxAckPending, &out.MaxAckPending
		*out = new(int64)
		**out = **in
	}
	if in.FlowControl != nil {
		in, out := &in.FlowControl, &out.FlowControl
		*out = new(bool)
		**out = **in
	}
	if in.HeadersOnly != nil {
		in, out := &in.HeadersOnly, &out.HeadersOnly
		*out = new(bool)
		**out = **in
	}
	if in.MaxRequestBatch != nil {
		in, out := &in.MaxRequestBatch, &out.MaxRequestBatch
		*out = new(int64)
		**out = **in
	}
	if in.MaxRequestExpires != nil {
		in, out := &in.MaxRequestExpires, &out.MaxRequestExpires
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxRequestMaxBytes != nil {
		in, out := &in.MaxRequestMaxBytes, &out.MaxRequestMaxBytes
		*out = new(int64)
		**out = **in
	}
	if in.Heartbeat != nil {
		in, out := &in.Heartbeat, &out.Heartbeat
		*out = new(v1.Duration)
		**out = **in
	}
	if in.InactiveThreshold != nil {
		in, out := &in.InactiveThreshold, &out.InactiveThreshold
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MemoryStorage != nil {
		in, out := &in.MemoryStorage, &out.MemoryStorage
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PauseUntil != nil {
		in, out := &in.PauseUntil, &out.PauseUntil
		*out = (*in).DeepCopy()
	}
	if in.PriorityGroups != nil {
		in, out := &in.PriorityGroups, &out.PriorityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PriorityPolicy != nil {
		in, out := &in.PriorityPolicy, &out.PriorityPolicy
		*out = new(PriorityPolicy)
		**out = **in
	}
	if in.PinnedTTL != nil {
		in, out := &in.PinnedTTL, &out.PinnedTTL
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerConfig.
func (in *ConsumerConfig) DeepCopy() *ConsumerConfig {
	if in == nil {
		return nil
	}
	out := new(ConsumerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerServerStatus) DeepCopyInto(out *ConsumerServerStatus) {
	*out = *in
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]ReplicaStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerServerStatus.
func (in *ConsumerServerStatus) DeepCopy() *ConsumerServerStatus {
	if in == nil {
		return nil
	}
	out := new(ConsumerServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvacuationSource) DeepCopyInto(out *EvacuationSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvacuationSource.
func (in *EvacuationSource) DeepCopy() *EvacuationSource {
	if in == nil {
		return nil
	}
	out := new(EvacuationSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvacuationTarget) DeepCopyInto(out *EvacuationTarget) {
	*out = *in
	if in.ServerTags != nil {
		in, out := &in.ServerTags, &out.ServerTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvacuationTarget.
func (in *EvacuationTarget) DeepCopy() *EvacuationTarget {
	if in == nil {
		return nil
	}
	out := new(EvacuationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalStream) DeepCopyInto(out *ExternalStream) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalStream.
func (in *ExternalStream) DeepCopy() *ExternalStream {
	if in == nil {
		return nil
	}
	out := new(ExternalStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyValueConfig) DeepCopyInto(out *KeyValueConfig) {
	*out = *in
	if in.MaxValueSize != nil {
		in, out := &in.MaxValueSize, &out.MaxValueSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = new(int32)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageType)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(Placement)
		(*in).DeepCopyInto(*out)
	}
	if in.Republish != nil {
		in, out := &in.Republish, &out.Republish
		*out = new(Republish)
		(*in).DeepCopyInto(*out)
	}
	if in.Mirror != nil {
		in, out := &in.Mirror, &out.Mirror
		*out = new(StreamSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]StreamSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(bool)
		**out = **in
	}
	if in.LimitMarkerTTL != nil {
		in, out := &in.LimitMarkerTTL, &out.LimitMarkerTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValueConfig.
func (in *KeyValueConfig) DeepCopy() *KeyValueConfig {
	if in == nil {
		return nil
	}
	out := new(KeyValueConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Move) DeepCopyInto(out *Move) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Move.
func (in *Move) DeepCopy() *Move {
	if in == nil {
		return nil
	}
	out := new(Move)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Moves) DeepCopyInto(out *Moves) {
	*out = *in
	if in.Leader != nil {
		in, out := &in.Leader, &out.Leader
		*out = new(bool)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Moves.
func (in *Moves) DeepCopy() *Moves {
	if in == nil {
		return nil
	}
	out := new(Moves)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsBalancer) DeepCopyInto(out *NatsBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsBalancer.
func (in *NatsBalancer) DeepCopy() *NatsBalancer {
	if in == nil {
		return nil
	}
	out := new(NatsBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsBalancerList) DeepCopyInto(out *NatsBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsBalancerList.
func (in *NatsBalancerList) DeepCopy() *NatsBalancerList {
	if in == nil {
		return nil
	}
	out := new(NatsBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsBalancerSpec) DeepCopyInto(out *NatsBalancerSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]Pool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Moves != nil {
		in, out := &in.Moves, &out.Moves
		*out = new(Moves)
		(*in).DeepCopyInto(*out)
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsBalancerSpec.
func (in *NatsBalancerSpec) DeepCopy() *NatsBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(NatsBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsBalancerStatus) DeepCopyInto(out *NatsBalancerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]PoolStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastMove != nil {
		in, out := &in.LastMove, &out.LastMove
		*out = new(Move)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsBalancerStatus.
func (in *NatsBalancerStatus) DeepCopy() *NatsBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(NatsBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsClusterEvacuation) DeepCopyInto(out *NatsClusterEvacuation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsClusterEvacuation.
func (in *NatsClusterEvacuation) DeepCopy() *NatsClusterEvacuation {
	if in == nil {
		return nil
	}
	out := new(NatsClusterEvacuation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsClusterEvacuation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsClusterEvacuationList) DeepCopyInto(out *NatsClusterEvacuationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsClusterEvacuation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsClusterEvacuationList.
func (in *NatsClusterEvacuationList) DeepCopy() *NatsClusterEvacuationList {
	if in == nil {
		return nil
	}
	out := new(NatsClusterEvacuationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsClusterEvacuationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsClusterEvacuationSpec) DeepCopyInto(out *NatsClusterEvacuationSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.From = in.From
	in.To.DeepCopyInto(&out.To)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsClusterEvacuationSpec.
func (in *NatsClusterEvacuationSpec) DeepCopy() *NatsClusterEvacuationSpec {
	if in == nil {
		return nil
	}
	out := new(NatsClusterEvacuationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsClusterEvacuationStatus) DeepCopyInto(out *NatsClusterEvacuationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Requested != nil {
		in, out := &in.Requested, &out.Requested
		*out = make([]RequestedMove, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pinned != nil {
		in, out := &in.Pinned, &out.Pinned
		*out = make([]PinnedObject, len(*in))
		copy(*out, *in)
	}
	if in.StalePlacement != nil {
		in, out := &in.StalePlacement, &out.StalePlacement
		*out = make([]ServerStream, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsClusterEvacuationStatus.
func (in *NatsClusterEvacuationStatus) DeepCopy() *NatsClusterEvacuationStatus {
	if in == nil {
		return nil
	}
	out := new(NatsClusterEvacuationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsConsumer) DeepCopyInto(out *NatsConsumer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsConsumer.
func (in *NatsConsumer) DeepCopy() *NatsConsumer {
	if in == nil {
		return nil
	}
	out := new(NatsConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsConsumer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsConsumerList) DeepCopyInto(out *NatsConsumerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsConsumer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsConsumerList.
func (in *NatsConsumerList) DeepCopy() *NatsConsumerList {
	if in == nil {
		return nil
	}
	out := new(NatsConsumerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsConsumerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsConsumerSpec) DeepCopyInto(out *NatsConsumerSpec) {
	*out = *in
	if in.ConnectionRef != nil {
		in, out := &in.ConnectionRef, &out.ConnectionRef
		*out = new(natsv1beta1.ObjectReference)
		**out = **in
	}
	if in.StreamRef != nil {
		in, out := &in.StreamRef, &out.StreamRef
		*out = new(natsv1beta1.ObjectReference)
		**out = **in
	}
	out.Policies = in.Policies
	if in.RecreateOnImmutableChange != nil {
		in, out := &in.RecreateOnImmutableChange, &out.RecreateOnImmutableChange
		*out = new(bool)
		**out = **in
	}
	in.ConsumerConfig.DeepCopyInto(&out.ConsumerConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsConsumerSpec.
func (in *NatsConsumerSpec) DeepCopy() *NatsConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(NatsConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsConsumerStatus) DeepCopyInto(out *NatsConsumerStatus) {
	*out = *in
	in.SyncStatus.DeepCopyInto(&out.SyncStatus)
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(ConsumerServerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsConsumerStatus.
func (in *NatsConsumerStatus) DeepCopy() *NatsConsumerStatus {
	if in == nil {
		return nil
	}
	out := new(NatsConsumerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsKeyValue) DeepCopyInto(out *NatsKeyValue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsKeyValue.
func (in *NatsKeyValue) DeepCopy() *NatsKeyValue {
	if in == nil {
		return nil
	}
	out := new(NatsKeyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsKeyValue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsKeyValueList) DeepCopyInto(out *NatsKeyValueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsKeyValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsKeyValueList.
func (in *NatsKeyValueList) DeepCopy() *NatsKeyValueList {
	if in == nil {
		return nil
	}
	out := new(NatsKeyValueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsKeyValueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsKeyValueSpec) DeepCopyInto(out *NatsKeyValueSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.Policies = in.Policies
	in.KeyValueConfig.DeepCopyInto(&out.KeyValueConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsKeyValueSpec.
func (in *NatsKeyValueSpec) DeepCopy() *NatsKeyValueSpec {
	if in == nil {
		return nil
	}
	out := new(NatsKeyValueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsKeyValueStatus) DeepCopyInto(out *NatsKeyValueStatus) {
	*out = *in
	in.SyncStatus.DeepCopyInto(&out.SyncStatus)
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(StreamServerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsKeyValueStatus.
func (in *NatsKeyValueStatus) DeepCopy() *NatsKeyValueStatus {
	if in == nil {
		return nil
	}
	out := new(NatsKeyValueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsObjectStore) DeepCopyInto(out *NatsObjectStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsObjectStore.
func (in *NatsObjectStore) DeepCopy() *NatsObjectStore {
	if in == nil {
		return nil
	}
	out := new(NatsObjectStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsObjectStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsObjectStoreList) DeepCopyInto(out *NatsObjectStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsObjectStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsObjectStoreList.
func (in *NatsObjectStoreList) DeepCopy() *NatsObjectStoreList {
	if in == nil {
		return nil
	}
	out := new(NatsObjectStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsObjectStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsObjectStoreSpec) DeepCopyInto(out *NatsObjectStoreSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.Policies = in.Policies
	in.ObjectStoreConfig.DeepCopyInto(&out.ObjectStoreConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsObjectStoreSpec.
func (in *NatsObjectStoreSpec) DeepCopy() *NatsObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(NatsObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsObjectStoreStatus) DeepCopyInto(out *NatsObjectStoreStatus) {
	*out = *in
	in.SyncStatus.DeepCopyInto(&out.SyncStatus)
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(StreamServerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsObjectStoreStatus.
func (in *NatsObjectStoreStatus) DeepCopy() *NatsObjectStoreStatus {
	if in == nil {
		return nil
	}
	out := new(NatsObjectStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsStream) DeepCopyInto(out *NatsStream) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsStream.
func (in *NatsStream) DeepCopy() *NatsStream {
	if in == nil {
		return nil
	}
	out := new(NatsStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsStream) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsStreamList) DeepCopyInto(out *NatsStreamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsStream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsStreamList.
func (in *NatsStreamList) DeepCopy() *NatsStreamList {
	if in == nil {
		return nil
	}
	out := new(NatsStreamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsStreamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsStreamSpec) DeepCopyInto(out *NatsStreamSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.Policies = in.Policies
	in.StreamConfig.DeepCopyInto(&out.StreamConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsStreamSpec.
func (in *NatsStreamSpec) DeepCopy() *NatsStreamSpec {
	if in == nil {
		return nil
	}
	out := new(NatsStreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsStreamStatus) DeepCopyInto(out *NatsStreamStatus) {
	*out = *in
	in.SyncStatus.DeepCopyInto(&out.SyncStatus)
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(StreamServerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Transfer != nil {
		in, out := &in.Transfer, &out.Transfer
		*out = new(StreamTransfer)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsStreamStatus.
func (in *NatsStreamStatus) DeepCopy() *NatsStreamStatus {
	if in == nil {
		return nil
	}
	out := new(NatsStreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSystemBalancer) DeepCopyInto(out *NatsSystemBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSystemBalancer.
func (in *NatsSystemBalancer) DeepCopy() *NatsSystemBalancer {
	if in == nil {
		return nil
	}
	out := new(NatsSystemBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsSystemBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSystemBalancerList) DeepCopyInto(out *NatsSystemBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsSystemBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSystemBalancerList.
func (in *NatsSystemBalancerList) DeepCopy() *NatsSystemBalancerList {
	if in == nil {
		return nil
	}
	out := new(NatsSystemBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsSystemBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSystemBalancerSpec) DeepCopyInto(out *NatsSystemBalancerSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.Moves != nil {
		in, out := &in.Moves, &out.Moves
		*out = new(Moves)
		(*in).DeepCopyInto(*out)
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSystemBalancerSpec.
func (in *NatsSystemBalancerSpec) DeepCopy() *NatsSystemBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(NatsSystemBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSystemBalancerStatus) DeepCopyInto(out *NatsSystemBalancerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(Capabilities)
		**out = **in
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]ServerLoad, len(*in))
		copy(*out, *in)
	}
	if in.Skew != nil {
		in, out := &in.Skew, &out.Skew
		*out = new(Skew)
		**out = **in
	}
	if in.LastMove != nil {
		in, out := &in.LastMove, &out.LastMove
		*out = new(Move)
		(*in).DeepCopyInto(*out)
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = make([]Move, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSystemBalancerStatus.
func (in *NatsSystemBalancerStatus) DeepCopy() *NatsSystemBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(NatsSystemBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreConfig) DeepCopyInto(out *ObjectStoreConfig) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageType)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(Placement)
		(*in).DeepCopyInto(*out)
	}
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreConfig.
func (in *ObjectStoreConfig) DeepCopy() *ObjectStoreConfig {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ownership) DeepCopyInto(out *Ownership) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ownership.
func (in *Ownership) DeepCopy() *Ownership {
	if in == nil {
		return nil
	}
	out := new(Ownership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinnedObject) DeepCopyInto(out *PinnedObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinnedObject.
func (in *PinnedObject) DeepCopy() *PinnedObject {
	if in == nil {
		return nil
	}
	out := new(PinnedObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Placement) DeepCopyInto(out *Placement) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Placement.
func (in *Placement) DeepCopy() *Placement {
	if in == nil {
		return nil
	}
	out := new(Placement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policies) DeepCopyInto(out *Policies) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policies.
func (in *Policies) DeepCopy() *Policies {
	if in == nil {
		return nil
	}
	out := new(Policies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pool) DeepCopyInto(out *Pool) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pool.
func (in *Pool) DeepCopy() *Pool {
	if in == nil {
		return nil
	}
	out := new(Pool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolStatus) DeepCopyInto(out *PoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolStatus.
func (in *PoolStatus) DeepCopy() *PoolStatus {
	if in == nil {
		return nil
	}
	out := new(PoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaStatus) DeepCopyInto(out *ReplicaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaStatus.
func (in *ReplicaStatus) DeepCopy() *ReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Republish) DeepCopyInto(out *Republish) {
	*out = *in
	if in.HeadersOnly != nil {
		in, out := &in.HeadersOnly, &out.HeadersOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Republish.
func (in *Republish) DeepCopy() *Republish {
	if in == nil {
		return nil
	}
	out := new(Republish)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestedMove) DeepCopyInto(out *RequestedMove) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestedMove.
func (in *RequestedMove) DeepCopy() *RequestedMove {
	if in == nil {
		return nil
	}
	out := new(RequestedMove)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerLoad) DeepCopyInto(out *ServerLoad) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerLoad.
func (in *ServerLoad) DeepCopy() *ServerLoad {
	if in == nil {
		return nil
	}
	out := new(ServerLoad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerStream) DeepCopyInto(out *ServerStream) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerStream.
func (in *ServerStream) DeepCopy() *ServerStream {
	if in == nil {
		return nil
	}
	out := new(ServerStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skew) DeepCopyInto(out *Skew) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skew.
func (in *Skew) DeepCopy() *Skew {
	if in == nil {
		return nil
	}
	out := new(Skew)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamConfig) DeepCopyInto(out *StreamConfig) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(RetentionPolicy)
		**out = **in
	}
	if in.MaxConsumers != nil {
		in, out := &in.MaxConsumers, &out.MaxConsumers
		*out = new(int64)
		**out = **in
	}
	if in.MaxMsgs != nil {
		in, out := &in.MaxMsgs, &out.MaxMsgs
		*out = new(int64)
		**out = **in
	}
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Discard != nil {
		in, out := &in.Discard, &out.Discard
		*out = new(DiscardPolicy)
		**out = **in
	}
	if in.DiscardNewPerSubject != nil {
		in, out := &in.DiscardNewPerSubject, &out.DiscardNewPerSubject
		*out = new(bool)
		**out = **in
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxMsgsPerSubject != nil {
		in, out := &in.MaxMsgsPerSubject, &out.MaxMsgsPerSubject
		*out = new(int64)
		**out = **in
	}
	if in.MaxMsgSize != nil {
		in, out := &in.MaxMsgSize, &out.MaxMsgSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageType)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NoAck != nil {
		in, out := &in.NoAck, &out.NoAck
		*out = new(bool)
		**out = **in
	}
	if in.Duplicates != nil {
		in, out := &in.Duplicates, &out.Duplicates
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(Placement)
		(*in).DeepCopyInto(*out)
	}
	if in.Mirror != nil {
		in, out := &in.Mirror, &out.Mirror
		*out = new(StreamSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]StreamSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sealed != nil {
		in, out := &in.Sealed, &out.Sealed
		*out = new(bool)
		**out = **in
	}
	if in.DenyDelete != nil {
		in, out := &in.DenyDelete, &out.DenyDelete
		*out = new(bool)
		**out = **in
	}
	if in.DenyPurge != nil {
		in, out := &in.DenyPurge, &out.DenyPurge
		*out = new(bool)
		**out = **in
	}
	if in.AllowRollup != nil {
		in, out := &in.AllowRollup, &out.AllowRollup
		*out = new(bool)
		**out = **in
	}
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(StoreCompression)
		**out = **in
	}
	if in.FirstSeq != nil {
		in, out := &in.FirstSeq, &out.FirstSeq
		*out = new(int64)
		**out = **in
	}
	if in.SubjectTransform != nil {
		in, out := &in.SubjectTransform, &out.SubjectTransform
		*out = new(SubjectTransform)
		**out = **in
	}
	if in.Republish != nil {
		in, out := &in.Republish, &out.Republish
		*out = new(Republish)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowDirect != nil {
		in, out := &in.AllowDirect, &out.AllowDirect
		*out = new(bool)
		**out = **in
	}
	if in.MirrorDirect != nil {
		in, out := &in.MirrorDirect, &out.MirrorDirect
		*out = new(bool)
		**out = **in
	}
	if in.ConsumerLimits != nil {
		in, out := &in.ConsumerLimits, &out.ConsumerLimits
		*out = new(StreamConsumerLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AllowMsgTTL != nil {
		in, out := &in.AllowMsgTTL, &out.AllowMsgTTL
		*out = new(bool)
		**out = **in
	}
	if in.SubjectDeleteMarkerTTL != nil {
		in, out := &in.SubjectDeleteMarkerTTL, &out.SubjectDeleteMarkerTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AllowMsgCounter != nil {
		in, out := &in.AllowMsgCounter, &out.AllowMsgCounter
		*out = new(bool)
		**out = **in
	}
	if in.AllowAtomicPublish != nil {
		in, out := &in.AllowAtomicPublish, &out.AllowAtomicPublish
		*out = new(bool)
		**out = **in
	}
	if in.AllowMsgSchedules != nil {
		in, out := &in.AllowMsgSchedules, &out.AllowMsgSchedules
		*out = new(bool)
		**out = **in
	}
	if in.PersistMode != nil {
		in, out := &in.PersistMode, &out.PersistMode
		*out = new(PersistMode)
		**out = **in
	}
	if in.AllowBatchPublish != nil {
		in, out := &in.AllowBatchPublish, &out.AllowBatchPublish
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamConfig.
func (in *StreamConfig) DeepCopy() *StreamConfig {
	if in == nil {
		return nil
	}
	out := new(StreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamConsumerLimits) DeepCopyInto(out *StreamConsumerLimits) {
	*out = *in
	if in.InactiveThreshold != nil {
		in, out := &in.InactiveThreshold, &out.InactiveThreshold
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxAckPending != nil {
		in, out := &in.MaxAckPending, &out.MaxAckPending
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamConsumerLimits.
func (in *StreamConsumerLimits) DeepCopy() *StreamConsumerLimits {
	if in == nil {
		return nil
	}
	out := new(StreamConsumerLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamConsumerSource) DeepCopyInto(out *StreamConsumerSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamConsumerSource.
func (in *StreamConsumerSource) DeepCopy() *StreamConsumerSource {
	if in == nil {
		return nil
	}
	out := new(StreamConsumerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamServerStatus) DeepCopyInto(out *StreamServerStatus) {
	*out = *in
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]ReplicaStatus, len(*in))
		copy(*out, *in)
	}
	if in.Bytes != nil {
		in, out := &in.Bytes, &out.Bytes
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamServerStatus.
func (in *StreamServerStatus) DeepCopy() *StreamServerStatus {
	if in == nil {
		return nil
	}
	out := new(StreamServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamSource) DeepCopyInto(out *StreamSource) {
	*out = *in
	if in.OptStartSeq != nil {
		in, out := &in.OptStartSeq, &out.OptStartSeq
		*out = new(int64)
		**out = **in
	}
	if in.OptStartTime != nil {
		in, out := &in.OptStartTime, &out.OptStartTime
		*out = (*in).DeepCopy()
	}
	if in.SubjectTransforms != nil {
		in, out := &in.SubjectTransforms, &out.SubjectTransforms
		*out = make([]SubjectTransform, len(*in))
		copy(*out, *in)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalStream)
		**out = **in
	}
	if in.Consumer != nil {
		in, out := &in.Consumer, &out.Consumer
		*out = new(StreamConsumerSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamSource.
func (in *StreamSource) DeepCopy() *StreamSource {
	if in == nil {
		return nil
	}
	out := new(StreamSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamTransfer) DeepCopyInto(out *StreamTransfer) {
	*out = *in
	if in.Started != nil {
		in, out := &in.Started, &out.Started
		*out = (*in).DeepCopy()
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]ReplicaStatus, len(*in))
		copy(*out, *in)
	}
	if in.Consumers != nil {
		in, out := &in.Consumers, &out.Consumers
		*out = new(TransferConsumers)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamTransfer.
func (in *StreamTransfer) DeepCopy() *StreamTransfer {
	if in == nil {
		return nil
	}
	out := new(StreamTransfer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectTransform) DeepCopyInto(out *SubjectTransform) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectTransform.
func (in *SubjectTransform) DeepCopy() *SubjectTransform {
	if in == nil {
		return nil
	}
	out := new(SubjectTransform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncStatus) DeepCopyInto(out *SyncStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedTime != nil {
		in, out := &in.LastSyncedTime, &out.LastSyncedTime
		*out = (*in).DeepCopy()
	}
	if in.NextCheckTime != nil {
		in, out := &in.NextCheckTime, &out.NextCheckTime
		*out = (*in).DeepCopy()
	}
	if in.Ownership != nil {
		in, out := &in.Ownership, &out.Ownership
		*out = new(Ownership)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncStatus.
func (in *SyncStatus) DeepCopy() *SyncStatus {
	if in == nil {
		return nil
	}
	out := new(SyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferConsumers) DeepCopyInto(out *TransferConsumers) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferConsumers.
func (in *TransferConsumers) DeepCopy() *TransferConsumers {
	if in == nil {
		return nil
	}
	out := new(TransferConsumers)
	in.DeepCopyInto(out)
	return out
}
