// Command telemetrydocs writes the documentation site's telemetry page: the
// environment the OpenTelemetry SDK reads, every instrument, the reconcile
// spans and the Kubernetes events.
package main

import (
	_ "embed"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/mikluko/nats-operator/internal/telemetry"
)

// page is the page's path from the repository root.
const page = "docs/content/docs/reference/telemetry.md"

//go:embed environment.md
var environment string

//go:embed otel-operator.md
var otelOperator string

// jwtExpiry is the account JWT expiry alert, a format taking the gauge's
// Prometheus name.
//
//go:embed jwtexpiry.md
var jwtExpiry string

func main() {
	out := flag.String("o", page, "file to write")
	flag.Parse()
	text, err := render()
	if err == nil {
		err = os.WriteFile(*out, []byte(text), 0o644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "telemetrydocs:", err)
		os.Exit(1)
	}
}

func render() (string, error) {
	var b strings.Builder
	b.WriteString(`---
title: Telemetry
weight: 3
description: The OpenTelemetry metrics and traces each controller exports, the environment that configures them, and the Kubernetes events the controllers record.
---

<!-- Generated by ` + "`just telemetry-docs`" + ` from hack/telemetrydocs and internal/telemetry. -->

Each controller exports metrics and traces through the OpenTelemetry Go SDK, configured by the environment alone; it has no flag of its own for them. A signal is exported only once one of ` + "`OTEL_<SIGNAL>_EXPORTER`" + `, ` + "`OTEL_EXPORTER_OTLP_<SIGNAL>_ENDPOINT`" + ` or ` + "`OTEL_EXPORTER_OTLP_ENDPOINT`" + ` is set, ` + "`<SIGNAL>`" + ` being ` + "`METRICS`" + ` or ` + "`TRACES`" + `; with none of them set, or with ` + "`OTEL_SDK_DISABLED=true`" + `, the controller exports nothing and the instruments below are not collected. Once a signal is on, it is sent as OTLP over ` + "`http/protobuf`" + ` to ` + "`https://localhost:4318`" + ` unless the variables below say otherwise, and a failed export is logged. controller-runtime's own Prometheus metrics are served apart, on ` + "`--metrics-bind-address`" + `.

`)
	b.WriteString(environment)
	b.WriteString(otelOperator)

	b.WriteString("\n## Metrics\n\nThe gauges are read off the resources' status at each export. Every point carries `kind`, `namespace` and `name` of the resource it describes. The Prometheus column is each instrument's name as `OTEL_METRICS_EXPORTER=prometheus` serves it on port 9464, which `metrics.prometheus.enabled` sets.\n\n")
	b.WriteString("| Instrument | Prometheus | Type | Unit | Controllers | Attributes | Reads | Value |\n|---|---|---|---|---|---|---|---|\n")
	for _, in := range telemetry.Instruments {
		prom, err := in.PrometheusName()
		if err != nil {
			return "", fmt.Errorf("instrument %s: %w", in.Name, err)
		}
		var unit []string
		if in.Unit != "" {
			unit = []string{in.Unit}
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s | %s | %s | %s | %s |\n",
			in.Name, prom, in.Type, code(unit, ""), strings.Join(in.Controllers, ", "), code(in.Attributes, ", "), in.Reads, in.Description)
	}
	expiry, err := telemetry.AccountJWTExpiry.PrometheusName()
	if err != nil {
		return "", fmt.Errorf("instrument %s: %w", telemetry.AccountJWTExpiry.Name, err)
	}
	fmt.Fprintf(&b, jwtExpiry, expiry)

	b.WriteString("\n## Traces\n\nEach reconcile runs in a span named `Reconcile <kind>`, such as `Reconcile NatsCluster`, carrying `kind`, `namespace` and `name`. A reconcile that returns an error marks its span failed with it.\n")

	b.WriteString("\n## Events\n\nThe controllers record these through the `events.k8s.io` API, regarding the resource named.\n\n")
	b.WriteString("| Reason | Type | Controller | Regarding | Recorded when |\n|---|---|---|---|---|\n")
	for _, e := range telemetry.Events {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", e.Reason, e.Type, e.Controller, code(e.Regarding, ", "), e.When)
	}
	return b.String(), nil
}

func code(list []string, sep string) string {
	quoted := make([]string, len(list))
	for i, s := range list {
		quoted[i] = "`" + s + "`"
	}
	return strings.Join(quoted, sep)
}
