//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	natsv1beta1 "github.com/mikluko/nats-operator/api/nats/v1beta1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountJetStreamLimits) DeepCopyInto(out *AccountJetStreamLimits) {
	*out = *in
	if in.MemoryStorage != nil {
		in, out := &in.MemoryStorage, &out.MemoryStorage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DiskStorage != nil {
		in, out := &in.DiskStorage, &out.DiskStorage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Streams != nil {
		in, out := &in.Streams, &out.Streams
		*out = new(int64)
		**out = **in
	}
	if in.Consumers != nil {
		in, out := &in.Consumers, &out.Consumers
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountJetStreamLimits.
func (in *AccountJetStreamLimits) DeepCopy() *AccountJetStreamLimits {
	if in == nil {
		return nil
	}
	out := new(AccountJetStreamLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountLimits) DeepCopyInto(out *AccountLimits) {
	*out = *in
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = new(int64)
		**out = **in
	}
	if in.Subscriptions != nil {
		in, out := &in.Subscriptions, &out.Subscriptions
		*out = new(int64)
		**out = **in
	}
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.JetStream != nil {
		in, out := &in.JetStream, &out.JetStream
		*out = new(AccountJetStreamLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountLimits.
func (in *AccountLimits) DeepCopy() *AccountLimits {
	if in == nil {
		return nil
	}
	out := new(AccountLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountReference) DeepCopyInto(out *AccountReference) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountReference.
func (in *AccountReference) DeepCopy() *AccountReference {
	if in == nil {
		return nil
	}
	out := new(AccountReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletedAccount) DeepCopyInto(out *DeletedAccount) {
	*out = *in
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletedAccount.
func (in *DeletedAccount) DeepCopy() *DeletedAccount {
	if in == nil {
		return nil
	}
	out := new(DeletedAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Distribution) DeepCopyInto(out *Distribution) {
	*out = *in
	if in.LastPushTime != nil {
		in, out := &in.LastPushTime, &out.LastPushTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Distribution.
func (in *Distribution) DeepCopy() *Distribution {
	if in == nil {
		return nil
	}
	out := new(Distribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Export) DeepCopyInto(out *Export) {
	*out = *in
	if in.Importers != nil {
		in, out := &in.Importers, &out.Importers
		*out = make([]AccountReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Export.
func (in *Export) DeepCopy() *Export {
	if in == nil {
		return nil
	}
	out := new(Export)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityKey) DeepCopyInto(out *IdentityKey) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityKey.
func (in *IdentityKey) DeepCopy() *IdentityKey {
	if in == nil {
		return nil
	}
	out := new(IdentityKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Import) DeepCopyInto(out *Import) {
	*out = *in
	out.AccountRef = in.AccountRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Import.
func (in *Import) DeepCopy() *Import {
	if in == nil {
		return nil
	}
	out := new(Import)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportStatus) DeepCopyInto(out *ImportStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportStatus.
func (in *ImportStatus) DeepCopy() *ImportStatus {
	if in == nil {
		return nil
	}
	out := new(ImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Keys) DeepCopyInto(out *Keys) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(IdentityKey)
		**out = **in
	}
	if in.Signing != nil {
		in, out := &in.Signing, &out.Signing
		*out = make([]SigningKey, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Keys.
func (in *Keys) DeepCopy() *Keys {
	if in == nil {
		return nil
	}
	out := new(Keys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccount) DeepCopyInto(out *NatsAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccount.
func (in *NatsAccount) DeepCopy() *NatsAccount {
	if in == nil {
		return nil
	}
	out := new(NatsAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountList) DeepCopyInto(out *NatsAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountList.
func (in *NatsAccountList) DeepCopy() *NatsAccountList {
	if in == nil {
		return nil
	}
	out := new(NatsAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountSpec) DeepCopyInto(out *NatsAccountSpec) {
	*out = *in
	out.OperatorRef = in.OperatorRef
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = new(Keys)
		(*in).DeepCopyInto(*out)
	}
	if in.JWTTTL != nil {
		in, out := &in.JWTTTL, &out.JWTTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(AccountLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]Export, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]Import, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountSpec.
func (in *NatsAccountSpec) DeepCopy() *NatsAccountSpec {
	if in == nil {
		return nil
	}
	out := new(NatsAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountStatus) DeepCopyInto(out *NatsAccountStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = new(Distribution)
		(*in).DeepCopyInto(*out)
	}
	if in.Revocations != nil {
		in, out := &in.Revocations, &out.Revocations
		*out = make([]Revocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]ImportStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountStatus.
func (in *NatsAccountStatus) DeepCopy() *NatsAccountStatus {
	if in == nil {
		return nil
	}
	out := new(NatsAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsOperator) DeepCopyInto(out *NatsOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsOperator.
func (in *NatsOperator) DeepCopy() *NatsOperator {
	if in == nil {
		return nil
	}
	out := new(NatsOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsOperatorList) DeepCopyInto(out *NatsOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsOperatorList.
func (in *NatsOperatorList) DeepCopy() *NatsOperatorList {
	if in == nil {
		return nil
	}
	out := new(NatsOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsOperatorSpec) DeepCopyInto(out *NatsOperatorSpec) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = new(Keys)
		(*in).DeepCopyInto(*out)
	}
	out.SystemAccountRef = in.SystemAccountRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsOperatorSpec.
func (in *NatsOperatorSpec) DeepCopy() *NatsOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(NatsOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsOperatorStatus) DeepCopyInto(out *NatsOperatorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SigningKeys != nil {
		in, out := &in.SigningKeys, &out.SigningKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SeedSecrets != nil {
		in, out := &in.SeedSecrets, &out.SeedSecrets
		*out = new(SeedSecrets)
		(*in).DeepCopyInto(*out)
	}
	if in.SystemAccount != nil {
		in, out := &in.SystemAccount, &out.SystemAccount
		*out = new(SystemAccountStatus)
		**out = **in
	}
	if in.DeletedAccounts != nil {
		in, out := &in.DeletedAccounts, &out.DeletedAccounts
		*out = make([]DeletedAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsOperatorStatus.
func (in *NatsOperatorStatus) DeepCopy() *NatsOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(NatsOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSystemAccount) DeepCopyInto(out *NatsSystemAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSystemAccount.
func (in *NatsSystemAccount) DeepCopy() *NatsSystemAccount {
	if in == nil {
		return nil
	}
	out := new(NatsSystemAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsSystemAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSystemAccountList) DeepCopyInto(out *NatsSystemAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsSystemAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSystemAccountList.
func (in *NatsSystemAccountList) DeepCopy() *NatsSystemAccountList {
	if in == nil {
		return nil
	}
	out := new(NatsSystemAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsSystemAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSystemAccountSpec) DeepCopyInto(out *NatsSystemAccountSpec) {
	*out = *in
	out.OperatorRef = in.OperatorRef
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = new(Keys)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSystemAccountSpec.
func (in *NatsSystemAccountSpec) DeepCopy() *NatsSystemAccountSpec {
	if in == nil {
		return nil
	}
	out := new(NatsSystemAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsSystemAccountStatus) DeepCopyInto(out *NatsSystemAccountStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = new(Distribution)
		(*in).DeepCopyInto(*out)
	}
	if in.Revocations != nil {
		in, out := &in.Revocations, &out.Revocations
		*out = make([]Revocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsSystemAccountStatus.
func (in *NatsSystemAccountStatus) DeepCopy() *NatsSystemAccountStatus {
	if in == nil {
		return nil
	}
	out := new(NatsSystemAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUser) DeepCopyInto(out *NatsUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUser.
func (in *NatsUser) DeepCopy() *NatsUser {
	if in == nil {
		return nil
	}
	out := new(NatsUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserList) DeepCopyInto(out *NatsUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserList.
func (in *NatsUserList) DeepCopy() *NatsUserList {
	if in == nil {
		return nil
	}
	out := new(NatsUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserSpec) DeepCopyInto(out *NatsUserSpec) {
	*out = *in
	out.AccountRef = in.AccountRef
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(Permissions)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionTypes != nil {
		in, out := &in.ConnectionTypes, &out.ConnectionTypes
		*out = make([]ConnectionType, len(*in))
		copy(*out, *in)
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(natsv1beta1.Credentials)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserSpec.
func (in *NatsUserSpec) DeepCopy() *NatsUserSpec {
	if in == nil {
		return nil
	}
	out := new(NatsUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserStatus) DeepCopyInto(out *NatsUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReplacedKeys != nil {
		in, out := &in.ReplacedKeys, &out.ReplacedKeys
		*out = make([]ReplacedKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserStatus.
func (in *NatsUserStatus) DeepCopy() *NatsUserStatus {
	if in == nil {
		return nil
	}
	out := new(NatsUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Permissions) DeepCopyInto(out *Permissions) {
	*out = *in
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(SubjectPermissions)
		(*in).DeepCopyInto(*out)
	}
	if in.Subscribe != nil {
		in, out := &in.Subscribe, &out.Subscribe
		*out = new(SubjectPermissions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Permissions.
func (in *Permissions) DeepCopy() *Permissions {
	if in == nil {
		return nil
	}
	out := new(Permissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplacedKey) DeepCopyInto(out *ReplacedKey) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplacedKey.
func (in *ReplacedKey) DeepCopy() *ReplacedKey {
	if in == nil {
		return nil
	}
	out := new(ReplacedKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Revocation) DeepCopyInto(out *Revocation) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
	if in.Issuers != nil {
		in, out := &in.Issuers, &out.Issuers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Revocation.
func (in *Revocation) DeepCopy() *Revocation {
	if in == nil {
		return nil
	}
	out := new(Revocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedSecretKeySelector) DeepCopyInto(out *SeedSecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedSecretKeySelector.
func (in *SeedSecretKeySelector) DeepCopy() *SeedSecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SeedSecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedSecrets) DeepCopyInto(out *SeedSecrets) {
	*out = *in
	if in.Signing != nil {
		in, out := &in.Signing, &out.Signing
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedSecrets.
func (in *SeedSecrets) DeepCopy() *SeedSecrets {
	if in == nil {
		return nil
	}
	out := new(SeedSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigningKey) DeepCopyInto(out *SigningKey) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigningKey.
func (in *SigningKey) DeepCopy() *SigningKey {
	if in == nil {
		return nil
	}
	out := new(SigningKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectPermissions) DeepCopyInto(out *SubjectPermissions) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectPermissions.
func (in *SubjectPermissions) DeepCopy() *SubjectPermissions {
	if in == nil {
		return nil
	}
	out := new(SubjectPermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemAccountStatus) DeepCopyInto(out *SystemAccountStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemAccountStatus.
func (in *SystemAccountStatus) DeepCopy() *SystemAccountStatus {
	if in == nil {
		return nil
	}
	out := new(SystemAccountStatus)
	in.DeepCopyInto(out)
	return out
}
