---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth-controller
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - auth.nats-operator.io
  resources:
  - natsaccounts
  - natsusers
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - auth.nats-operator.io
  resources:
  - natsaccounts/status
  - natsoperators/status
  - natssystemaccounts/status
  - natsusers/finalizers
  - natsusers/status
  verbs:
  - update
- apiGroups:
  - auth.nats-operator.io
  resources:
  - natsoperators
  - natssystemaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - nats-operator.io
  resources:
  - natsaccounttrusts
  - natsconnections
  - natsoperatortrusts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nats-operator.io
  resources:
  - natsaccounttrusts/status
  - natsoperatortrusts/status
  verbs:
  - update
- apiGroups:
  - nats-operator.io
  resources:
  - natsreferencegrants
  verbs:
  - list
  - watch
