apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: orders-service
  namespace: nats-system
spec:
  accountRef:
    kind: NatsAccount
    name: orders
  permissions:
    publish:
      allow: ["orders.>", "$JS.API.>"]
    subscribe:
      allow: ["orders.>", "_INBOX.>"]
  credentials:
    secretKeyRef:
      name: orders-service-creds
---
apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: orders-batch
  namespace: nats-system
spec:
  accountRef:
    kind: NatsAccount
    name: orders
  publicKey: UDXU4RCSJNZOIQHZNWXHXORDPRTGNJAHAHFRGZNEEJCPQTT2M7NLCNF4
  permissions:
    publish:
      allow: ["orders.batch.>"]
---
apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: orders-jetstream
  namespace: nats-system
spec:
  accountRef:
    kind: NatsAccount
    name: orders
  permissions:
    publish:
      allow: ["$JS.API.>"]
    subscribe:
      allow: ["_INBOX.>"]
  credentials:
    secretKeyRef:
      name: orders-jetstream-creds
---
apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: cluster-controller
  namespace: nats-system
spec:
  accountRef:
    kind: NatsSystemAccount
    name: sys
  preset: cluster-controller
  credentials:
    secretKeyRef:
      name: cluster-controller-creds
---
apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: jetstream-controller
  namespace: nats-system
spec:
  accountRef:
    kind: NatsSystemAccount
    name: sys
  preset: jetstream-controller
  credentials:
    secretKeyRef:
      name: jetstream-controller-creds
---
apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: auth-controller
  namespace: nats-system
spec:
  accountRef:
    kind: NatsSystemAccount
    name: sys
  preset: auth-controller
  credentials:
    secretKeyRef:
      name: auth-controller-creds
