apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: payments-reader
  namespace: orders
spec:
  accountRef:
    kind: NatsAccount
    namespace: nats-system
    name: payments
  preset: readonly
  credentials:
    secretKeyRef:
      name: payments-reader-creds
