apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: payments-api
  namespace: payments
spec:
  accountRef:
    kind: NatsAccount
    namespace: nats-system
    name: payments
  permissions:
    publish:
      allow: ["payments.>", "$JS.API.>"]
    subscribe:
      allow: ["payments.>", "_INBOX.>"]
  credentials:
    secretKeyRef:
      name: payments-api-creds
---
apiVersion: auth.nats.mikluko.io/v1beta1
kind: NatsUser
metadata:
  name: payments-jetstream
  namespace: payments
spec:
  accountRef:
    kind: NatsAccount
    namespace: nats-system
    name: payments
  permissions:
    publish:
      allow: ["$JS.API.>"]
    subscribe:
      allow: ["_INBOX.>"]
  credentials:
    secretKeyRef:
      name: payments-jetstream-creds
---
apiVersion: nats.mikluko.io/v1beta1
kind: NatsConnection
metadata:
  name: demo
  namespace: payments
spec:
  servers: ["nats://demo.nats-system.svc:4222"]
  credentials:
    secretKeyRef:
      name: payments-jetstream-creds
---
apiVersion: jetstream.nats.mikluko.io/v1beta1
kind: NatsStream
metadata:
  name: payments
  namespace: payments
spec:
  connectionRef:
    name: demo
  name: PAYMENTS
  subjects: ["payments.>"]
  storage: File
  replicas: 3
  maxAge: 720h
