// Command permdocs writes the documentation site's NATS permissions page:
// the subjects each controller requests and the presets that grant them.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/text"

	"github.com/mikluko/nats-operator/internal/jwtplane"
)

// page is the page's path from the repository root.
const page = "docs/content/docs/reference/nats-permissions.md"

func main() {
	out := flag.String("o", page, "file to write")
	flag.Parse()
	text, err := render()
	if err == nil {
		err = os.WriteFile(*out, []byte(text), 0o644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "permdocs:", err)
		os.Exit(1)
	}
}

const frontMatter = `---
title: NATS permissions
weight: 2
description: The nats-server subjects each controller requests, and the presets that grant them.
---

`

func render() (string, error) {
	draft, err := body(nil)
	if err != nil {
		return "", err
	}
	text, err := body(presetAnchors(draft))
	if err != nil {
		return "", err
	}
	return frontMatter + text, nil
}

// presetAnchors returns the anchor of each third-level heading of page, by
// its text, as goldmark's automatic heading IDs number a repeated one.
func presetAnchors(page string) map[string]string {
	src := []byte(page)
	doc := goldmark.New(goldmark.WithParserOptions(parser.WithAutoHeadingID())).Parser().Parse(text.NewReader(src))
	anchors := map[string]string{}
	for n := doc.FirstChild(); n != nil; n = n.NextSibling() {
		h, ok := n.(*ast.Heading)
		if !ok || h.Level != 3 {
			continue
		}
		id, ok := h.AttributeString("id")
		if !ok {
			continue
		}
		var name strings.Builder
		for c := h.FirstChild(); c != nil; c = c.NextSibling() {
			if t, ok := c.(*ast.Text); ok {
				name.Write(t.Value(src))
			}
		}
		anchors[name.String()] = string(id.([]byte))
	}
	return anchors
}

// body writes the page below its front matter, linking each identity's
// preset to its heading's entry in anchors, or to nothing when anchors is
// nil.
func body(anchors map[string]string) (string, error) {
	var b strings.Builder
	b.WriteString(`<!-- Generated by ` + "`just perm-docs`" + ` from hack/permdocs and internal/jwtplane. -->

Each controller takes every reply under its own preset's inbox: ` + inboxes() + `.
Each controller preset allows its own inbox and no other.
In a subject, ` + "`*`" + ` is one token that the controller fills in, such as a server ID, an account public key, or a stream or consumer name.
`)
	for _, id := range identities {
		fmt.Fprintf(&b, "\n## %s\n\n%s", id.Heading, id.Connection)
		if id.Preset != "" {
			anchor, ok := anchors[string(id.Preset)]
			if !ok && anchors != nil {
				return "", fmt.Errorf("preset %q of %s has no heading", id.Preset, id.Heading)
			}
			fmt.Fprintf(&b, " Preset: [`%s`](#%s).", id.Preset, anchor)
		}
		b.WriteString("\n\n| Subject | Use | Code |\n|---|---|---|\n")
		for _, c := range id.Calls {
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", c.Subject, c.Use, code(c.Sources))
		}
	}

	b.WriteString("\n## User presets\n\nA `NatsUser` with `spec.preset` gets exactly these claims, and sets neither `spec.permissions` nor `spec.connectionTypes`.\n")
	for _, p := range jwtplane.UserPresets() {
		if err := userPreset(&b, p); err != nil {
			return "", err
		}
	}

	exports, err := jwtplane.ExportPreset(jwtplane.ExportPresetJetStreamStepdown)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&b, "\n## Export preset\n\n### %s\n\n", jwtplane.ExportPresetJetStreamStepdown)
	b.WriteString("A `NatsAccount` export with `preset: jetstream-stepdown` expands to these service exports.\n" +
		"For each, the auth controller adds the matching import to the system account of the `NatsOperator` that signs the account, prefixed with `acc.<account public key>.`.\n\n")
	b.WriteString("| Export | Subject | System account imports it as |\n|---|---|---|\n")
	imports := jwtplane.StepdownImports("*")
	for i, e := range exports {
		fmt.Fprintf(&b, "| `%s` | `%s` | `%s` |\n", e.Name, e.Subject, imports[i].LocalSubject)
	}
	return b.String(), nil
}

// userPreset writes the section of preset p, and fails for a p jwtplane
// does not define.
func userPreset(b *strings.Builder, p jwtplane.UserPreset) error {
	g, ok := jwtplane.UserPresetGrant(p)
	if !ok {
		return fmt.Errorf("user preset %q has no grant", p)
	}
	fmt.Fprintf(b, "\n### %s\n\n%s\n", p, holders(g))
	fmt.Fprintf(b, "\nPublish: %s.\n\nSubscribe: %s.\n", subjects(g.Publish), subjects(g.Subscribe))
	if len(g.ConnectionTypes) > 0 {
		fmt.Fprintf(b, "\nConnection types: %s.\n", subjects(g.ConnectionTypes))
	}
	return nil
}

// inboxes lists the inbox subject of each preset an identity names.
func inboxes() string {
	var parts []string
	for _, id := range identities {
		if id.Preset != "" {
			parts = append(parts, fmt.Sprintf("`%s.>`", jwtplane.InboxPrefix(id.Preset)))
		}
	}
	return strings.Join(parts, ", ")
}

func code(sources []string) string {
	quoted := make([]string, len(sources))
	for i, s := range sources {
		if s == natsGo {
			quoted[i] = "nats.go `jetstream`"
		} else {
			quoted[i] = "`" + s + "`"
		}
	}
	return strings.Join(quoted, ", ")
}

func holders(g jwtplane.PresetGrant) string {
	switch {
	case g.AnyAccount:
		return "For a user of any account."
	case g.SystemAccount:
		return "For a system account user."
	default:
		return "For a user of an ordinary account."
	}
}

func subjects(list []string) string {
	if len(list) == 0 {
		return "unrestricted"
	}
	quoted := make([]string, len(list))
	for i, s := range list {
		quoted[i] = "`" + s + "`"
	}
	return strings.Join(quoted, ", ")
}
